### ISSUE TITLE
Implement Star check

### ISSUE THREAD

**Issue by mjsonofharry** [lazerzes/TeamContentsMayBeHot#5]
A very important requirement is that a tree can only have one star. When a user wants to decorate a tree with a star with a new star you must print a warning that the tree already has a star and not add the price of a star to tree. Users must be able to continue decorating their tree if they add another star to it:
`Tree already has a star!`

**Comment by sensdoggo** [comment]
Star Check done in treebuilder() method. which is used to add new decorations.

*hey its the builder pattern* well kinda
